<a href="https://colab.research.google.com/github/guizyre/Final_Projeto_assert/blob/main/exercicio3.4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import scipy.linalg as sla

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
c = np.array([7,8,9]).reshape(1,3)

In [9]:
print('a: ',a.shape)
print('c: ',c.shape)

a:  (3,)
c:  (1, 3)


In [10]:
A = np.array([[2,3,5],[1,-1,10],[-1,1,-1]])

b = np.array([10,20,5])

In [11]:
np.linalg.matrix_rank(A)

np.int64(3)

In [12]:
np.linalg.matrix_rank(np.c_[A, b])

np.int64(3)

In [13]:
A.shape[1]

3

# **INICIO DO EXERCICIO 3.4**

# **Questão 1.1**

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,1,1])
np.linalg.matrix_rank(a)


np.int64(2)

In [15]:
np.linalg.matrix_rank(np.c_[a, b])


np.int64(2)

In [16]:
a.shape[1]

3

# **Assim a questão 1.1 é um sistema possivel indeterminado**

# **Questão 1.2**

In [17]:
a = np.array([[2,3],[-4,-6]])
b = np.array([10,-10])
np.linalg.matrix_rank(a)

np.int64(1)

In [18]:
np.linalg.matrix_rank(np.c_[a, b])


np.int64(2)

In [19]:
a.shape[1]

2

# **Assim é um sistema impossivel**

In [20]:
def sist_lin_diagonal(A,b): return b/A.diagonal()

In [21]:
A = np.diag([1,4,2])
b = np.array([4, 2, 2])

In [22]:
sist_lin_diagonal(A,b)

array([4. , 0.5, 1. ])

In [23]:
np.empty(3).shape

(3,)

In [24]:
np.array([]).shape

(0,)

In [25]:
A = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])

b = np.array([-10,-1,3,2])

# **Exercicio 1.2**

In [26]:
import numpy as np

A = np.array([
    [3.0, 4.0, -5.0,  1.0],
    [0.0, 1.0,  1.0, -2.0],
    [0.0, 0.0,  4.0, -5.0],
    [0.0, 0.0,  0.0,  2.0]
])
b = np.array([-10.0, -1.0, 3.0, 2.0])
x = np.zeros(4)
x[3] = b[3] / A[3, 3]
x[2] = (b[2] - (A[2, 3] * x[3])) / A[2, 2]
x[1] = (b[1] - (A[1, 2] * x[2] + A[1, 3] * x[3])) / A[1, 1]
x[0] = (b[0] - (A[0, 1] * x[1] + A[0, 2] * x[2] + A[0, 3] * x[3])) / A[0, 0]
print(x)

[ 1. -1.  2.  1.]


# **exercicio1.3**

In [27]:
import numpy as np

A2 = np.array([
    [3.0, 0.0, 0.0, 0.0],
    [2.0, 1.0, 0.0, 0.0],
    [1.0, 0.0, 1.0, 0.0],
    [1.0, 1.0, 1.0, 1.0]
])

b2 = np.array([4.0, 2.0, 4.0, 2.0])
x = np.zeros(4)

x[0] = b2[0] / A2[0, 0]
x[1] = (b2[1] - (A2[1, 0] * x[0])) / A2[1, 1]
x[2] = (b2[2] - (A2[2, 0] * x[0] + A2[2, 1] * x[1])) / A2[2, 2]
x[3] = (b2[3] - (A2[3, 0] * x[0] + A2[3, 1] * x[1] + A2[3, 2] * x[2])) / A2[3, 3]

print(x)


[ 1.33333333 -0.66666667  2.66666667 -1.33333333]


# **exercicio 1.4**

In [28]:
import numpy as np

def resolver_sistema_trivial(A, b):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    abaixo_zero = np.allclose(np.tril(A, -1), 0)
    acima_zero = np.allclose(np.triu(A, 1), 0)

    if np.any(np.isclose(np.diag(A), 0)):
        raise ValueError("sistema sem solução única.")

    if abaixo_zero and acima_zero:
        print("Matriz Diagonal")
        return b / np.diag(A)

    elif abaixo_zero:
        print("Triangular Superior Substituição Retroativa")
        x = np.zeros(n)
        for i in range(n - 1, -1, -1):
            soma = np.sum(A[i, i + 1:] * x[i + 1:])
            x[i] = (b[i] - soma) / A[i, i]
        return x

    elif acima_zero:
        print("Triangular Inferior Substituição Progressiva")
        x = np.zeros(n)
        for i in range(n):
            soma = np.sum(A[i, :i] * x[:i])
            x[i] = (b[i] - soma) / A[i, i]
        return x

    else:
        raise ValueError("A matriz não é diagonal, nem triangular superior ou inferior.")

In [29]:
#Sistema Triangular Superior Exemplo 3.2 e 3.4
A_sup = np.array([
    [3.0, 4.0, -5.0,  1.0],
    [0.0, 1.0,  1.0, -2.0],
    [0.0, 0.0,  4.0, -5.0],
    [0.0, 0.0,  0.0,  2.0]
])
b_sup = np.array([-10.0, -1.0, 3.0, 2.0])

sol_sup = resolver_sistema_trivial(A_sup, b_sup)
print("Solução:", sol_sup)

# Sistema Triangular Inferior Exemplo 3.4
A_inf = np.array([
    [3.0, 0.0, 0.0, 0.0],
    [2.0, 1.0, 0.0, 0.0],
    [1.0, 0.0, 1.0, 0.0],
    [1.0, 1.0, 1.0, 1.0]
])
b_inf = np.array([4.0, 2.0, 4.0, 2.0])

sol_inf = resolver_sistema_trivial(A_inf, b_inf)
print("Solução:", sol_inf)

#Sistema Diagonal
A_diag = np.array([
    [2.0, 0.0, 0.0],
    [0.0, 5.0, 0.0],
    [0.0, 0.0, -4.0]
])
b_diag = np.array([4.0, 15.0, 8.0])

sol_diag = resolver_sistema_trivial(A_diag, b_diag)
print("Solução:", sol_diag)


Triangular Superior Substituição Retroativa
Solução: [ 1. -1.  2.  1.]
Triangular Inferior Substituição Progressiva
Solução: [ 1.33333333 -0.66666667  2.66666667 -1.33333333]
Matriz Diagonal
Solução: [ 2.  3. -2.]
